raw_data_dir: "raw_data"
output_dir: "output_data"
local_dir: "safe_files"
country_config:
  country: "Latvia"
  year: 2021
  months: [1,12]
  product_type: "L1C"
  max_requested_products: 1000
  satellite: "S2"
workers: 16
chunk_size: 20
multiplier: 15