base_name: "latvia_portugal_vs_estonia"
data_dir: "preprocess"
random_seed: 42
num_samples:
  train:
    - 1
    - 5
    - 10
    - 20
    - 100
    - 200
    - 500
    - "all"
  validation: 1000
  test: "all"

meadow_class: 3302000000

pretrain_classes:
  region:
    - 3301010402
    - 3302000000
    - 3301060401
    - 3301010401
    - 3301010101
    - 3301010500
    - 3301010102
    - 3301110000
    - 3303020300
    - 3303011500
    - 3303010200
    - 3301020100
    - 3301030000
    - 3301990000
    - 3301090303
    - 3301130000
    - 3301010300
    - 3301061200
    - 3303020000
    - 3301210100
    - 3303021000
    - 3303020800
    - 3301020600
    - 3301090209
    - 3301150200
    - 3303000000
    - 3301010600
    - 3303020400
    - 3301140000
    - 3301070000
    - 3301090301
    - 3301220200
    - 3301140300
    - 3301010801
    - 3303011200
    - 3303010400
    - 3303070000
    - 3301290300
    - 3301290200
    - 3303020700
    - 3301210500
    - 3301290600
    - 3303080500
    - 3303020600
    - 3301230000
    - 3301060403
    - 3301010802
    - 3303021300
    - 3301220000
    - 3303080400
    - 3301061203
    - 3301061000
    - 3301090205
    - 3301210200
    - 3301061400
    - 3303060000
    - 3301020700
    - 3301140100
    - 3301011500
    - 3301061219
    - 3303010600
    - 3301081900
    - 3301011400
    - 3301200000
    - 3303020500
    - 3306080000
    - 3303020100
    - 3303020200
    - 3301060702
    - 3301290400
    - 3301061227
    - 3301011001
    - 3301290500
    - 3301180000
    - 3303011300
    - 3301090202
    - 3301061300
    - 3301061209
    - 3301090305
    - 3301160000
    - 3306020000
    - 3301082600
    - 3301020300
    - 3301061213
    - 3301280000
    - 3301061210
    - 3301011002
    - 3301210204
    - 3399000000
    - 3301061211
    - 3301290800
    - 3301220300
    - 3301250000
    - 3301210400
    - 3301310700
    - 3301090208
    - 3301061215
    - 3306000000
    - 3301310800
    - 3301300100
    - 3301310000
    - 3301060701
    - 3301310200
    - 3301090100
    - 3303080700
    - 3303050000
    - 3301140400
    - 3303010000
    - 3303011100
    - 3301010100
    - 3303120000
    - 3303030200
    - 3303040000
    - 3301019900
    - 3303010700
    - 3301061228
    - 3301010900
    - 3306060000
    - 3303030100
    - 3303030000
    - 3303030500
    - 3301140600
    - 3301010700
    - 3301010800
    - 3301020200
    - 3301210300
    - 3301010400
    - 3301040000
    - 3301220400
    - 3303100000
    - 3303030400
    - 3306050000
    - 3303010300
    - 3303011400
    - 3301060500
    - 3301060400
    - 3303990000
    - 3301080000
    - 3301090300
    - 3301140500
    - 3301260000
    - 3301060800


finetune_classes:
  region:
    - 3302000000
    - 3301010101
    - 3301090303
    - 3301020600
    - 3301010401
    - 3301060401
    - 3301010402
    - 3301070000
    - 3301110000
    - 3303010000
    - 3301030000
    - 3301010500
    - 3301010102
    - 3399000000
    - 3301150200
    - 3301020000
    - 3303021000
    - 3301090300
    - 3301290400
    - 3301090304
    - 3301210100
    - 3301090205
    - 3301090301
    - 3301130000
    - 3303010200
    - 3303020400
    - 3301011500
    - 3301020100
    - 3301010300
    - 3301230000
    - 3301060402
    - 3301010801
    - 3301010802
    - 3303070000
    - 3301061215
    - 3303020800
    - 3303020300
    - 3306080000
    - 3301290200
    - 3301010600
    - 3301140400
    - 3301140100
    - 3303020100
    - 3301061200
    - 3303021100
    - 3303060000
    - 3301220200
    - 3301210212
    - 3301061001
    - 3303011300
    - 3303011500
    - 3301061203
    - 3301290700
    - 3301080000
    - 3301290500
    - 3301220400
    - 3301290300
    - 3303011200
    - 3301061227
    - 3301061209
    - 3301081700
    - 3301210500
    - 3301290800
    - 3301061300
    - 3301200000
    - 3301060702
    - 3301061210
    - 3303020000
    - 3303010400
    - 3301019900
    - 3301081900
    - 3301210200
    - 3301180000
    - 3303080500
    - 3301060403
    - 3301990000
    - 3301061219
    - 3303020500
    - 3301060500
    - 3301010900
    - 3301090305
    - 3306000000
    - 3303020700
    - 3301061208
    - 3301081400
    - 3301290600
    - 3301120000
    - 3301083700
    - 3301210204
    - 3301011000
    - 3301210208
    - 3301250200
    - 3301061600
    - 3301061234
    - 3301210202
    - 3301310000
    - 3301280000
    - 3301020200
    - 3301020500
    - 3301081000
    - 3301060200
    - 3304030000
    - 3301300100
    - 3301061000
    - 3301061223
    - 3301061213
    - 3301310200
    - 3303030200
    - 3303990000
    - 3301061222
    - 3301069900
    - 3301061204
    - 3303020600
    - 3301083500
    - 3301061220
    - 3301170000
    - 3301061226
    - 3303021300
    - 3301220300
    - 3301310400
    - 3301061239
    - 3301061205
    - 3301061212
    - 3301210400
    - 3301140300
    - 3301140500
    - 3301250000


pretrain_regions:
  - "LV008"
  - "LV007"
  - "LV003"
  - "LV009"
  - "LV006"
  - "LV005"
  - "PT11"
  - "PT15"
  - "PT16"
  - "PT17"
  - "PT18"

finetune_regions: 
  - "EE"